blank_issues_enabled: false
contact_links:
  - name: AI dashboard Issue tracker
    url: https://github.com/racelandshop/ai-facial-dashboard/issues
    about: For issues and feature requests related to AI Dashboard
