name: "Test build"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: 16

jobs:
  build_frontend:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.8.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: script/bootstrap
      - name: Build
        run: script/build
